server:
  port: 1919

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CARMICROSERVICE
          uri: lb://CARMICROSERVICE
          predicates:
            - Path=/cars/**
          filters:
            - StripPrefix=1
        - id: RESERVATIONMICROSERVICE
          uri: lb://RESERVATIONMICROSERVICE
          predicates:
            - Path=/reservations/**
          filters:
            - StripPrefix=1
        - id: LOCATIONMICROSERVICE
          uri: lb://LOCATIONMICROSERVICE
          predicates:
            - Path=/locations/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
